### ISSUE TITLE
URL with "filter=errorOnly" (permalink-problem?) doesnt work correctly

### ISSUE THREAD

**Issue by dex2000** [ypid/opening_hours_map#31]
Steps to reproduce:
* Goto somewhere like here: http://openingh.openstreetmap.de/?zoom=18&lat=48.19384&lon=16.35112&layers=B0T&filter=none&tags=opening_hours
* click Checkbox: Errors only
* Click Permalink, you got: http://openingh.openstreetmap.de/?zoom=18&lat=48.19395&lon=16.35118&layers=B0T&filter=errorOnly&tags=opening_hours
* filter "errors" doesnt work on the Map nor in the checkboxes

Deutsch:
Wenn  ich ich die Checkbox "Nur Fehler" auswähle und auf den Permalink klicke bekomme ich zwar eine scheinbar korrekte URL mit &filter=errorOnly aber weder ist danach diе checkbox ausgewählt noch weiss die Karte etwas davon.

**Comment by dex2000** [comment]
Meh. Cannot reproduce it again :(

Deutsch. Jetzt schaue ich nochmal und finde das Problem nicht mehr :(
Ich schau mir das morgen nochmal an.

**Comment by dex2000** [comment]
Nochmal Meh. :)
Die Karte funktioniert mit dem Permalink scheinbar korrekt, die nicht korrekt ausgewählten Checkboxen haben mich mal wieder verwirrt. Wobei man das Problem bestimmt auch irgendwie mit Js totschlagen kann.

**Comment by ypid** [comment]
Stimmt. Die "Nur Fehler" Checkbox wird nicht ausgewählt. Ansonsten funktioniert es aber wie beabsichtig. Schaue ich mir bei gelegenheit mal an. Danke :smile:

**Comment by dex2000** [comment]
bugreport ... 20 min later developer-answer ... there is something wrong ;)

Böhmische Dörfer für mich, aber schaut trotzdem recht simpel aus: http://stackoverflow.com/questions/11454630/auto-checkbox-based-from-url-value-using-javascript-jquery

Vlt kannste was damit anfangen.
