### ISSUE TITLE
JOSM-QAT no connection

### ISSUE THREAD

**Issue by dex2000** [ypid/opening_hours_map#39]
On click on download in qat i get: "Die Internetverbindung funktioniert nicht"
Osmi, Keepright and Osmose works fine.

Josm 8800+java8+win7

**Comment by ypid** [comment]
Interessant. Da ist mir offenbar die Serverkomponente abgestützt. Ich schaue es mir mal an.

Service crashed :flushed: Looking into it …

```
undefined:1
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
^
SyntaxError: Unexpected token <
    at Object.parse (native)
    at IncomingMessage.<anonymous> (/home/ypid/opening_hours_server.js/ohs.js:232:40)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:929:16
    at process._tickCallback (node.js:419:13)
make: *** [serve] Fehler 8
```

**Comment by ypid** [comment]
Fixed. Thanks.

**Comment by dex2000** [comment]
looft.

**Comment by mmd-osm** [comment]
Do you have an example for an invalid JSON returned by Overpass API? That shouldn't happen in the first place.

**Comment by ypid** [comment]
@mmd-osm Thanks for the response. Seems to me that http://overpass-api.de/ is running with Apache as reverse proxy so I would suspect that the Overpass API was restarted once this error in the https://github.com/opening-hours/opening_hours_server.js happened. The string which was returned instead of the JSON was `<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">`.

The exception happened at: 2015-10-17T22:11:39+02:00
If it would be helpful I can provide the exact URL parameters send to the https://github.com/opening-hours/opening_hours_server.js (and thus also to the Overpass API).

**Comment by mmd-osm** [comment]
Yes, Apache is running to call the Overpass binaries via CGI. Sometimes, if a request takes too much time, the CGI timeout may hit first and you'll get some XML/HTML error message back. AFAICS there was no server issue or restart at that time. Do you provide a specific user agent which would facilitate identifying your request?

The exact URL parameters would be interesting, of course, especially if this reproducible and not related to some timeout or overload situation. Can you put them in an overpass turbo link, if possible? Thanks in advance.

**Comment by ypid** [comment]
> Do you run your queries with a specific user agent, which would facilitate identifying your request?

I do that now. https://github.com/opening-hours/opening_hours_server.js/commit/da70656afe976159810fb65e1ee5834431b01ea5

I will check the logs.

**Comment by ypid** [comment]
All right. I debugged this further and it seems that the opening-hours/opening_hours_server.js did get a 429 too many requests and tried to parse that as JSON. I was able to reproduce this. The query in the logs was a large one:

    api/oh_interpreter?&tag=collection_times&s=43.0746978&w=-5.7779135&n=55.6264312&e=23.6559225&filter=error

which resulted into this query:

    [out:json][timeout:300][bbox:43.0746978,-5.7779135,55.6264312,23.6559225];
    (node['collection_times'];way['collection_times'];);out body center;
