### ISSUE TITLE
translation problems "(listopada|listopad)" in pl version

### ISSUE THREAD

**Issue by matkoniecz** [ypid/opening_hours_map#41]
https://www.openstreetmap.org/node/2554310978 viewed in http://ypid.de/~osm/?zoom=16&lat=50.07983&lon=19.88411&layers=B0T&tags=opening_hours using browser requesting pl version results in

> but will close today, 20 (listopada|listopad), in 34 minutes.

> (listopada|listopad)

is bad

> listopada

would be good

> listopad

would be generally worse, but even that would be better that (listopada|listopad)

**Comment by ypid** [comment]
Thanks for reporting. Seems like the moment lib which is used has two definitions which are returned:

```
[ '(stycznia|styczeń)',
  '(lutego|luty)',
  '(marca|marzec)',
  '(kwietnia|kwiecień)',
  '(maja|maj)',
  '(czerwca|czerwiec)',
  '(lipca|lipiec)',
  '(sierpnia|sierpień)',
  '(września|wrzesień)',
  '(października|październik)',
  '(listopada|listopad)',
  '(grudnia|grudzień)' ]
```

Source code of `node_modules/moment/locale/pl.js` says the first one is `monthsNominative`, second is `monthsSubjective`. Can you confirm that all `monthsNominative` are the correct once in this sentence?

BTW, you you want to translate the other parts of the project too :wink: https://github.com/ypid/opening_hours.js#translating ?

**Comment by matkoniecz** [comment]
> Can you confirm that all monthsNominative are the correct once in for sentence?

Yes, I am confirming this.

> BTW, do you want to translate the other parts of the project too :wink: https://github.com/ypid/opening_hours.js#translating ?

It is on my (hilariously long) TODO list.

**Comment by ypid** [comment]
> It is on my (hilariously long) TODO list.

I know what you mean :smile:
